export const skills = {
        basic: {
          id: "basic",
          name: "기본 공격",
          type: "attack",
          power: 10,
          powerText: "위력 10 / 적 메인 1명",
          desc: "기본 피해를 준다.",
        },
        slash: {
          id: "slash",
          name: "일섬",
          type: "attack",
          power: 18,
          powerText: "위력 18 / 적 메인 1명",
          desc: "빠르게 베어 큰 피해를 준다.",
        },
        guard: {
          id: "guard",
          name: "철벽 자세",
          type: "guard",
          guardRate: 0.5,
          powerText: "피해 감소 50% / 자신",
          desc: "다음에 받는 피해를 50% 줄인다.",
        },
        halfmoon: {
          id: "halfmoon",
          name: "반월참",
          type: "attackBuff",
          power: 11,
          buff: 6,
          powerText: "위력 11 / 다음 공격 +6",
          desc: "피해를 주고 다음 공격 피해를 강화한다.",
        },
        fireball: {
          id: "fireball",
          name: "화염구",
          type: "attack",
          power: 21,
          powerText: "위력 21 / 적 메인 1명",
          desc: "강한 마법 피해를 준다.",
        },
        ice: {
          id: "ice",
          name: "얼음창",
          type: "attackDebuff",
          power: 14,
          debuff: 6,
          powerText: "위력 14 / 다음 공격 피해 -6",
          desc: "피해를 주고 상대의 다음 공격 피해를 줄인다.",
        },
        heal: {
          id: "heal",
          name: "치유의 빛",
          type: "heal",
          heal: 24,
          powerText: "회복 24 / 자신",
          desc: "자신의 HP를 회복한다.",
        },
        poison: {
          id: "poison",
          name: "독침",
          type: "poisonAttack",
          power: 11,
          powerText: "위력 11 / 독 3턴",
          desc: "피해를 주고 상대를 독 상태로 만든다.",
        },
        weak: {
          id: "weak",
          name: "급소 찌르기",
          type: "weakAttack",
          power: 14,
          bonusIfPoison: 10,
          powerText: "위력 14 / 독 상태면 +10",
          desc: "상대가 독 상태면 추가 피해를 준다.",
        },
        smoke: {
          id: "smoke",
          name: "연막",
          type: "evasion",
          powerText: "회피 40% / 자신",
          desc: "다음 공격을 40% 확률로 회피한다.",
        },
        shield_bash: {
          id: "shield_bash",
          name: "방패 강타",
          type: "attackDebuff",
          power: 11,
          debuff: 4,
          powerText: "위력 11 / 다음 공격 피해 -4",
          desc: "방패로 공격하고 상대의 다음 공격을 약화한다.",
        },
        fortress: {
          id: "fortress",
          name: "수호 자세",
          type: "guard",
          guardRate: 0.5,
          powerText: "피해 감소 50% / 자신",
          desc: "다음에 받는 피해를 절반 줄인다.",
        },
        heavy_strike: {
          id: "heavy_strike",
          name: "묵직한 일격",
          type: "attack",
          power: 15,
          powerText: "위력 15 / 적 메인 1명",
          desc: "느리지만 묵직한 일격을 가한다.",
        },
        berserk_axe: {
          id: "berserk_axe",
          name: "광란의 도끼",
          type: "attack",
          power: 22,
          powerText: "위력 22 / 적 메인 1명",
          desc: "강력한 도끼 공격을 가한다.",
        },
        blood_slash: {
          id: "blood_slash",
          name: "피의 참격",
          type: "attackBuff",
          power: 13,
          buff: 6,
          powerText: "위력 13 / 다음 공격 +6",
          desc: "피를 끓어오르게 해 다음 공격을 강화한다.",
        },
        rage: {
          id: "rage",
          name: "분노 폭발",
          type: "attackBuff",
          power: 7,
          buff: 7,
          powerText: "위력 7 / 다음 공격 +7",
          desc: "약한 피해를 주고 다음 공격을 강화한다.",
        },
        priest_heal: {
          id: "priest_heal",
          name: "치유",
          type: "heal",
          heal: 31,
          powerText: "회복 31 / 자신",
          desc: "자신의 HP를 크게 회복한다.",
        },
        judgment: {
          id: "judgment",
          name: "빛의 심판",
          type: "attack",
          power: 16,
          powerText: "위력 16 / 적 메인 1명",
          desc: "성스러운 빛으로 피해를 준다.",
        },
        blessing: {
          id: "blessing",
          name: "축복",
          type: "attackBuff",
          power: 6,
          buff: 7,
          powerText: "위력 6 / 다음 공격 +7",
          desc: "약한 피해를 주고 다음 공격을 강화한다.",
        },
        pierce_arrow: {
          id: "pierce_arrow",
          name: "관통 화살",
          type: "attack",
          power: 18,
          powerText: "위력 18 / 적 메인 1명",
          desc: "날카로운 화살로 안정적인 피해를 준다.",
        },
        rapid_shot: {
          id: "rapid_shot",
          name: "연속 사격",
          type: "attack",
          power: 15,
          powerText: "위력 15 / 적 메인 1명",
          desc: "빠른 사격으로 피해를 준다.",
        },
        focus_aim: {
          id: "focus_aim",
          name: "집중 조준",
          type: "attackBuff",
          power: 8,
          buff: 9,
          powerText: "위력 8 / 다음 공격 +9",
          desc: "가벼운 피해를 주고 다음 공격을 크게 강화한다.",
        },
        curse: {
          id: "curse",
          name: "저주",
          type: "attackDebuff",
          power: 9,
          debuff: 7,
          powerText: "위력 9 / 다음 공격 피해 -7",
          desc: "저주를 걸어 상대의 다음 공격을 약화한다.",
        },
        soul_drain: {
          id: "soul_drain",
          name: "영혼 흡수",
          type: "attack",
          power: 16,
          powerText: "위력 16 / 적 메인 1명",
          desc: "영혼을 갉아먹는 피해를 준다.",
        },
        dark_orb: {
          id: "dark_orb",
          name: "암흑 구체",
          type: "attack",
          power: 20,
          powerText: "위력 20 / 적 메인 1명",
          desc: "어둠의 구체로 큰 피해를 준다.",
        },
      };

export const characters = {
        검사: {
          name: "검사",
          hp: 118,
          atk: 16,
          def: 9,
          passiveName: "검의 호흡",
          passiveDesc: "공격 시 20% 확률로 추가 피해 8",
          skillIds: ["slash", "guard", "halfmoon"],
          subSkill: { id: "sub_warrior_cheer", name: "전열 격려", type: "allyAtkBuff", buff: 6, target: "allySingleMain", desc: "아군 메인 1명의 다음 공격 피해 +6" },
          ultimate: {
            name: "진 일섬",
            desc: "적 메인 1명에게 위력 44 피해",
            type: "attack",
            power: 44,
            target: "enemySingle",
          },
        },
        마법사: {
          name: "마법사",
          hp: 88,
          atk: 20,
          def: 4,
          passiveName: "마력 순환",
          passiveDesc: "자신의 3번째 행동마다 공격 스킬 피해 +10",
          skillIds: ["fireball", "ice", "heal"],
          subSkill: { id: "sub_mage_mana", name: "마력 보조", type: "allyUltimateGauge", gain: 1, target: "allySingleMain", desc: "아군 메인 1명의 궁극기 게이지 +1" },
          ultimate: {
            name: "메테오",
            desc: "적 메인 2명에게 위력 20 피해",
            type: "attack",
            power: 20,
            target: "enemyAllMain",
          },
        },
        도적: {
          name: "도적",
          hp: 96,
          atk: 14,
          def: 6,
          passiveName: "그림자 걸음",
          passiveDesc: "공격받을 때 15% 확률로 공격 회피",
          skillIds: ["poison", "weak", "smoke"],
          subSkill: { id: "sub_rogue_ambush", name: "기습 지원", type: "enemyDamage", damage: 9, target: "enemySingleMain", desc: "적 메인 1명에게 9 피해" },
          ultimate: {
            name: "그림자 난무",
            desc: "적 메인 1명에게 위력 40 피해, 대상이 독 상태면 추가 피해 8",
            type: "weakAttack",
            power: 40,
            bonusIfPoison: 8,
            target: "enemySingle",
          },
        },
        탱커: {
          name: "탱커",
          hp: 148,
          atk: 10,
          def: 14,
          passiveName: "불굴의 육체",
          passiveDesc: "HP가 40% 이하일 때 받는 피해 20% 감소",
          skillIds: ["shield_bash", "fortress", "heavy_strike"],
          subSkill: { id: "sub_tanker_protect", name: "보호 태세", type: "allyGuard", guardRate: 0.35, target: "allySingleMain", desc: "아군 메인 1명이 다음에 받는 피해 35% 감소" },
          ultimate: {
            name: "철벽의 수호",
            desc: "아군 메인 2명이 다음에 받는 피해 50% 감소",
            type: "teamGuard",
            guardRate: 0.5,
            target: "allyAllMain",
          },
        },
        광전사: {
          name: "광전사",
          hp: 98,
          atk: 21,
          def: 5,
          passiveName: "피의 갈망",
          passiveDesc: "HP가 50% 이하일 때 공격 피해 +10",
          skillIds: ["berserk_axe", "blood_slash", "rage"],
          subSkill: { id: "sub_berserker_rage", name: "분노 주입", type: "allyAtkBuffSelfHarm", buff: 8, selfDamage: 6, target: "allySingleMain", desc: "아군 메인 1명의 다음 공격 피해 +8, 대신 HP 6 감소" },
          ultimate: {
            name: "광폭화",
            desc: "적 메인 1명에게 위력 48 피해, 자신도 12 피해",
            type: "selfHarmAttack",
            power: 48,
            selfDamage: 12,
            target: "enemySingle",
          },
        },
        성직자: {
          name: "성직자",
          hp: 102,
          atk: 9,
          def: 8,
          passiveName: "성스러운 가호",
          passiveDesc: "회복 스킬의 회복량 20% 증가",
          skillIds: ["priest_heal", "judgment", "blessing"],
          subSkill: { id: "sub_priest_emergency_heal", name: "응급 치유", type: "allyHeal", heal: 30, target: "allySingleMain", desc: "아군 메인 1명 HP 30 회복" },
          ultimate: {
            name: "대치유",
            desc: "아군 메인 2명의 HP를 32 회복",
            type: "teamHeal",
            heal: 32,
            target: "allyAllMain",
          },
        },
        궁수: {
          name: "궁수",
          hp: 100,
          atk: 17,
          def: 6,
          passiveName: "매의 눈",
          passiveDesc: "공격 시 15% 확률로 추가 피해 10",
          skillIds: ["pierce_arrow", "rapid_shot", "focus_aim"],
          subSkill: { id: "sub_archer_cover", name: "엄호 사격", type: "enemyDamage", damage: 11, target: "enemySingleMain", desc: "적 메인 1명에게 11 피해" },
          ultimate: {
            name: "폭풍 사격",
            desc: "적 메인 2명에게 위력 20 피해",
            type: "attack",
            power: 20,
            target: "enemyAllMain",
          },
        },
        주술사: {
          name: "주술사",
          hp: 92,
          atk: 16,
          def: 5,
          passiveName: "저주의 낙인",
          passiveDesc: "독 또는 공격감소 상태의 적에게 피해 +8",
          skillIds: ["curse", "soul_drain", "dark_orb"],
          subSkill: { id: "sub_shaman_curse", name: "약화 저주", type: "enemyAtkDebuff", debuff: 6, target: "enemySingleMain", desc: "적 메인 1명의 다음 공격 피해 -6" },
          ultimate: {
            name: "파멸의 저주",
            desc: "적 메인 1명에게 위력 39 피해, 공격 감소 8, 독 3턴",
            type: "poisonDebuffAttack",
            power: 39,
            debuff: 8,
            poison: 3,
            target: "enemySingle",
          },
        },
      };
