export const skills = {
        basic: {
          id: "basic",
          name: "기본 공격",
          type: "attack",
          power: 10,
          powerText: "위력 10 / 적 메인 1명",
          desc: "기본 피해를 준다.",
        },
        slash: {
          id: "slash",
          name: "일섬",
          type: "attack",
          power: 20,
          powerText: "위력 20 / 적 메인 1명",
          desc: "빠르게 베어 큰 피해를 준다.",
        },
        guard: {
          id: "guard",
          name: "철벽 자세",
          type: "guard",
          guardRate: 0.5,
          powerText: "피해 감소 50% / 자신",
          desc: "다음에 받는 피해를 50% 줄인다.",
        },
        halfmoon: {
          id: "halfmoon",
          name: "반월참",
          type: "attackBuff",
          power: 12,
          buff: 7,
          powerText: "위력 12 / 다음 공격 +7",
          desc: "피해를 주고 다음 공격 피해를 강화한다.",
        },
        fireball: {
          id: "fireball",
          name: "화염구",
          type: "attack",
          power: 23,
          powerText: "위력 23 / 적 메인 1명",
          desc: "강한 마법 피해를 준다.",
        },
        ice: {
          id: "ice",
          name: "얼음창",
          type: "attackDebuff",
          power: 15,
          debuff: 6,
          powerText: "위력 15 / 다음 공격 피해 -6",
          desc: "피해를 주고 상대의 다음 공격 피해를 줄인다.",
        },
        heal: {
          id: "heal",
          name: "치유의 빛",
          type: "heal",
          heal: 25,
          powerText: "회복 25 / 자신",
          desc: "자신의 HP를 회복한다.",
        },
        poison: {
          id: "poison",
          name: "독침",
          type: "poisonAttack",
          power: 10,
          powerText: "위력 10 / 독 3턴",
          desc: "피해를 주고 상대를 독 상태로 만든다.",
        },
        weak: {
          id: "weak",
          name: "급소 찌르기",
          type: "weakAttack",
          power: 16,
          bonusIfPoison: 12,
          powerText: "위력 16 / 독 상태면 +12",
          desc: "상대가 독 상태면 추가 피해를 준다.",
        },
        smoke: {
          id: "smoke",
          name: "연막",
          type: "evasion",
          powerText: "회피 40% / 자신",
          desc: "다음 공격을 40% 확률로 회피한다.",
        },
        shield_bash: {
          id: "shield_bash",
          name: "방패 강타",
          type: "attackDebuff",
          power: 12,
          debuff: 5,
          powerText: "위력 12 / 다음 공격 피해 -5",
          desc: "방패로 공격하고 상대의 다음 공격을 약화한다.",
        },
        fortress: {
          id: "fortress",
          name: "수호 자세",
          type: "guard",
          guardRate: 0.6,
          powerText: "피해 감소 60% / 자신",
          desc: "다음에 받는 피해를 크게 줄인다.",
        },
        heavy_strike: {
          id: "heavy_strike",
          name: "묵직한 일격",
          type: "attack",
          power: 18,
          powerText: "위력 18 / 적 메인 1명",
          desc: "느리지만 강한 일격을 가한다.",
        },
        berserk_axe: {
          id: "berserk_axe",
          name: "광란의 도끼",
          type: "attack",
          power: 28,
          powerText: "위력 28 / 적 메인 1명",
          desc: "강력한 도끼 공격을 가한다.",
        },
        blood_slash: {
          id: "blood_slash",
          name: "피의 참격",
          type: "attackBuff",
          power: 16,
          buff: 6,
          powerText: "위력 16 / 다음 공격 +6",
          desc: "피를 끓어오르게 해 다음 공격을 강화한다.",
        },
        rage: {
          id: "rage",
          name: "분노 폭발",
          type: "attackBuff",
          power: 8,
          buff: 10,
          powerText: "위력 8 / 다음 공격 +10",
          desc: "약한 피해를 주고 다음 공격을 크게 강화한다.",
        },
        priest_heal: {
          id: "priest_heal",
          name: "치유",
          type: "heal",
          heal: 32,
          powerText: "회복 32 / 자신",
          desc: "자신의 HP를 크게 회복한다.",
        },
        judgment: {
          id: "judgment",
          name: "빛의 심판",
          type: "attack",
          power: 18,
          powerText: "위력 18 / 적 메인 1명",
          desc: "성스러운 빛으로 피해를 준다.",
        },
        blessing: {
          id: "blessing",
          name: "축복",
          type: "attackBuff",
          power: 5,
          buff: 8,
          powerText: "위력 5 / 다음 공격 +8",
          desc: "약한 피해를 주고 다음 공격을 강화한다.",
        },
        pierce_arrow: {
          id: "pierce_arrow",
          name: "관통 화살",
          type: "attack",
          power: 19,
          powerText: "위력 19 / 적 메인 1명",
          desc: "날카로운 화살로 안정적인 피해를 준다.",
        },
        rapid_shot: {
          id: "rapid_shot",
          name: "연속 사격",
          type: "attack",
          power: 16,
          powerText: "위력 16 / 적 메인 1명",
          desc: "빠른 사격으로 피해를 준다.",
        },
        focus_aim: {
          id: "focus_aim",
          name: "집중 조준",
          type: "attackBuff",
          power: 7,
          buff: 12,
          powerText: "위력 7 / 다음 공격 +12",
          desc: "가벼운 피해를 주고 다음 공격을 크게 강화한다.",
        },
        curse: {
          id: "curse",
          name: "저주",
          type: "attackDebuff",
          power: 8,
          debuff: 8,
          powerText: "위력 8 / 다음 공격 피해 -8",
          desc: "저주를 걸어 상대의 다음 공격을 약화한다.",
        },
        soul_drain: {
          id: "soul_drain",
          name: "영혼 흡수",
          type: "attack",
          power: 17,
          powerText: "위력 17 / 적 메인 1명",
          desc: "영혼을 갉아먹는 피해를 준다.",
        },
        dark_orb: {
          id: "dark_orb",
          name: "암흑 구체",
          type: "attack",
          power: 22,
          powerText: "위력 22 / 적 메인 1명",
          desc: "어둠의 구체로 큰 피해를 준다.",
        },
      };

      export const characters = {
        검사: {
          name: "검사",
          hp: 110,
          atk: 15,
          def: 8,
          passiveName: "검의 호흡",
          passiveDesc: "공격 시 20% 확률로 추가 피해 8",
          skillIds: ["slash", "guard", "halfmoon"],
        },
        마법사: {
          name: "마법사",
          hp: 80,
          atk: 22,
          def: 3,
          passiveName: "마력 순환",
          passiveDesc: "자신의 3번째 행동마다 공격 스킬 피해 +10",
          skillIds: ["fireball", "ice", "heal"],
        },
        도적: {
          name: "도적",
          hp: 90,
          atk: 13,
          def: 5,
          passiveName: "그림자 걸음",
          passiveDesc: "공격받을 때 15% 확률로 공격 회피",
          skillIds: ["poison", "weak", "smoke"],
        },
        탱커: {
          name: "탱커",
          hp: 150,
          atk: 9,
          def: 15,
          passiveName: "불굴의 육체",
          passiveDesc: "HP가 40% 이하일 때 받는 피해 20% 감소",
          skillIds: ["shield_bash", "fortress", "heavy_strike"],
        },
        광전사: {
          name: "광전사",
          hp: 105,
          atk: 22,
          def: 4,
          passiveName: "피의 갈망",
          passiveDesc: "HP가 50% 이하일 때 공격 피해 +10",
          skillIds: ["berserk_axe", "blood_slash", "rage"],
        },
        성직자: {
          name: "성직자",
          hp: 95,
          atk: 10,
          def: 7,
          passiveName: "성스러운 가호",
          passiveDesc: "회복 스킬의 회복량 20% 증가",
          skillIds: ["priest_heal", "judgment", "blessing"],
        },
        궁수: {
          name: "궁수",
          hp: 90,
          atk: 17,
          def: 5,
          passiveName: "매의 눈",
          passiveDesc: "공격 시 15% 확률로 추가 피해 10",
          skillIds: ["pierce_arrow", "rapid_shot", "focus_aim"],
        },
        주술사: {
          name: "주술사",
          hp: 85,
          atk: 16,
          def: 4,
          passiveName: "저주의 낙인",
          passiveDesc: "독 또는 공격감소 상태의 적에게 피해 +8",
          skillIds: ["curse", "soul_drain", "dark_orb"],
        },
      };

      let currentMode = null;
      let currentRoomCode = null;
      let mySide = null;
      let partySelection = [];
      let singlePartyState = null;
      let latestOnlineBattle = null;
      let partyBusy = false;
      let pendingPartySkillId = null;
